"""
Music Generation Tool definition.

This module defines tools for generating music using the Suno API.
"""

from crewai.tools import tool
import json
import os
from dotenv import load_dotenv

# Import the SunoTool from our tools package
from tools.suno_tool import SunoTool

# Load environment variables
load_dotenv()

def create_music_generation_tool():
    """
    Create and return music generation tools.
    
    Returns:
        tuple: (generate_music_tool, download_music_tool)
    """
    # Check for Suno API key
    SUNO_API_KEY = os.getenv("SUNO_API_KEY")
    if not SUNO_API_KEY:
        raise ValueError("ERROR: Suno API key is required. Set SUNO_API_KEY environment variable.")

    # Create a global instance of the Suno tool
    suno_tool_instance = SunoTool()

    @tool("Generate music tool")
    def generate_music(prompt: str, artist_data: str = None, style: str = None) -> str:
        """Generate music using the Suno API based on an artist's style or a specific prompt.
        
        Args:
            prompt: The main prompt describing the music to generate
            artist_data: Optional JSON string with artist information to inform the generation
            style: Optional specific style description to apply
        
        Returns:
            A JSON string with the generation result
        """
        try:
            # Check for API key again at runtime
            if not os.getenv("SUNO_API_KEY"):
                return json.dumps({"error": "ERROR: Suno API key is missing. Please set the SUNO_API_KEY environment variable."}, indent=2)
                
            # Process artist data if provided
            title = "Generated Track"
            genre = []
            style_prompt = style or ""
            
            if artist_data:
                try:
                    # Parse the artist data JSON
                    artist_info = json.loads(artist_data)
                    
                    # Extract useful information for the music generation
                    if "name" in artist_info:
                        title = f"Inspired by {artist_info['name']}"
                    
                    if "genre" in artist_info and isinstance(artist_info["genre"], list):
                        genre = artist_info["genre"]
                    
                    # Build a rich style prompt from the style keywords if available
                    if "style_keywords" in artist_info and isinstance(artist_info["style_keywords"], list):
                        # Extract just the keywords or use the full objects depending on format
                        keywords = []
                        for item in artist_info["style_keywords"]:
                            if isinstance(item, dict) and "keyword" in item:
                                keywords.append(item["keyword"])
                            elif isinstance(item, str):
                                keywords.append(item)
                        
                        if keywords:
                            style_prompt += " " + ", ".join(keywords[:10])  # Limit to 10 keywords
                except json.JSONDecodeError:
                    # If JSON parsing fails, just use the artist_data as part of the prompt
                    style_prompt += f" {artist_data}"
            
            # Generate the music
            result = suno_tool_instance.generate_music(
                prompt=prompt,
                title=title,
                style_prompt=style_prompt,
                genre=genre[:3] if genre else None,  # Limit to 3 genres
                wait_for_completion=True
            )
            
            # Return the result as a JSON string
            return json.dumps(result, indent=2)
        
        except Exception as e:
            return json.dumps({"error": f"Error generating music: {str(e)}"}, indent=2)

    @tool("Download music tool")
    def download_music(generation_id: str, output_path: str = None) -> str:
        """Download music that was generated by the Suno API.
        
        Args:
            generation_id: The ID of the generated music to download
            output_path: Optional path to save the audio file
        
        Returns:
            A JSON string with the download result
        """
        try:
            # Check for API key again at runtime
            if not os.getenv("SUNO_API_KEY"):
                return json.dumps({"error": "ERROR: Suno API key is missing. Please set the SUNO_API_KEY environment variable."}, indent=2)
            
            # Use a default output path if none provided
            if not output_path:
                output_path = f"suno_generation_{generation_id}.mp3"
            
            # Download the audio
            result = suno_tool_instance.download_audio(
                generation_id=generation_id,
                output_path=output_path
            )
            
            # Return the result as a JSON string
            return json.dumps(result, indent=2)
        
        except Exception as e:
            return json.dumps({"error": f"Error downloading music: {str(e)}"}, indent=2)
    
    return generate_music, download_music 